@startuml
participant ZygoteInit as "ZygoteInit.java"
participant Zygote as "Zygote.java"
participant WrapperInit as "WrapperInit.java"
participant RuntimeInit as "RuntimeInit.java"


--> ZygoteInit : startSystemServer\n(abiList, socketName)
activate ZygoteInit
ZygoteInit -> ZygoteInit : init Args : \ncapabilities,uid,gid,nice-name\
    \nruntime-args,debugger,invoke-with
ZygoteInit -> Zygote : forkSystemServer(...)
deactivate ZygoteInit

activate Zygote
Zygote -> ZygoteInit : return pid
ref over Zygote : fork_system_server.puml
deactivate Zygote

activate ZygoteInit
alt pid
else pid == 0 //in child process

ZygoteInit -> ZygoteInit : handleSystemServerProcess(parsedArgs)

group handleSystemServerProcess
    ZygoteInit -> ZygoteInit : closeServerSocket();
    ZygoteInit -> ZygoteInit : set nice name
    ZygoteInit -> ZygoteInit : init systemServerClasspath
    ZygoteInit -> ZygoteInit : performSystemServerDexOpt()
    deactivate ZygoteInit

    alt parsedArgs.invokeWith

    note right of ZygoteInit : parsedArgs.invokeWith specifies different application runner

    ref over ZygoteInit : app_start_wrapper.puml

    else Not Null

        note right of ZygoteInit : run system server with new wrapper from beginning
        ZygoteInit -> WrapperInit : execApplication(...);

        activate WrapperInit
        WrapperInit -> Zygote : execShell(command.toString)\
        \n// wrapper args to string\
        \n//execute /system/bin/app_process64
        deactivate WrapperInit

        activate Zygote
        Zygote --> Zygote : execute command\
         \nstart from app_main.cpp :: main()

        ref over Zygote : zygote_start.puml
        deactivate Zygote

    else Null

        note right of ZygoteInit : run system server with zygote


        activate ZygoteInit
        ZygoteInit -> ZygoteInit : ClassLoader cl = \
        \nnew PathClassLoader(systemServerClasspath,\
        \nClassLoader.getSystemClassLoader());

        ZygoteInit -> ZygoteInit : Thread.currentThread().setContextClassLoader(cl)

        ZygoteInit -> RuntimeInit : zygoteInit(parsedArgs.targetSdkVersion, parsedArgs.remainingArgs, cl);
        deactivate ZygoteInit

        activate RuntimeInit
        RuntimeInit --> RuntimeInit : start system server from zygote

        ref over RuntimeInit : runtime_init.puml
        deactivate RuntimeInit

    end
end

end


@enduml