@startuml
participant ActivityThread as "ActivityThread.java"
participant Instrumentation as "Instrumentation.java"
participant Activity as "Activity.java"

-> ActivityThread : handleResumeActivity()

activate ActivityThread

ActivityThread -> ActivityThread : performResumeActivity(token, clearHide)

group performResumeActivity

ActivityThread -> ActivityThread : ActivityClientRecord r = mActivities.get(token);

    alt r
    else r != null && !r.activity.mFinished

        ActivityThread -> ActivityThread : r.activity.onStateNotSaved();

        ActivityThread -> ActivityThread : r.activity.mFragments.noteStateNotSaved();

        ActivityThread -> ActivityThread : deliverNewIntents(r, r.pendingIntents);//if need

        ActivityThread -> ActivityThread : deliverResults(r, r.pendingResults);//if need

        ActivityThread -> Activity : r.activity.performResume();

        deactivate ActivityThread
        activate Activity

        Activity -> Activity : performRestart();

        group performRestart

            Activity -> Activity : mFragments.noteStateNotSaved();

            alt mStopped //resume from stopped state
            else true
                Activity -> Activity : WindowManagerGlobal.getInstance().\
                \n setStoppedState(mToken, false);

                Activity -> Activity : mCalled = false;

                Activity -> Activity : callActivityOnRestart(this);\
                \n//just dispatching call onRestart() to activity here

            end


            Activity -> Activity :

        end

        Activity -> Activity :
        Activity -> Activity :
        Activity -> Activity :
        Activity -> Activity :

        ActivityThread -> ActivityThread : r.paused = false;
        ActivityThread -> ActivityThread : r.stopped = false;
        ActivityThread -> ActivityThread : r.state = null;
        ActivityThread -> ActivityThread : r.persistentState = null;
    end

end
ActivityThread -> ActivityThread :

ActivityThread -> ActivityThread :


deactivate ActivityThread
@enduml